CREATE OR REPLACE FUNCTION log_temuan_trigger()
RETURNS TRIGGER AS $$
BEGIN
    -- Check if WAKTU_AC_ATASAN is being updated
    IF NEW."WAKTU_AC_ATASAN" IS DISTINCT FROM OLD."WAKTU_AC_ATASAN" THEN
        INSERT INTO "LOG_TEMUAN" ("ID_TARGET", "LOG_KIRIM", "WAKTU") 
        VALUES (NEW."ID_TEMUAN", NEW."LOG_KIRIM", CURRENT_TIMESTAMP);
    END IF;
    
    -- Check if WAKTU_AC_AUDITOR is being updated
    IF NEW."WAKTU_AC_AUDITOR" IS DISTINCT FROM OLD."WAKTU_AC_AUDITOR" THEN
        INSERT INTO "LOG_TEMUAN" ("ID_TARGET", "LOG_KIRIM", "WAKTU") 
        VALUES (NEW."ID_TEMUAN", NEW."LOG_KIRIM", CURRENT_TIMESTAMP);
    END IF;
    
    -- Check if WAKTU_AC_LEADAUDITOR is being updated
    IF NEW."WAKTU_AC_LEADAUDITOR" IS DISTINCT FROM OLD."WAKTU_AC_LEADAUDITOR" THEN
        INSERT INTO "LOG_TEMUAN" ("ID_TARGET", "LOG_KIRIM", "WAKTU") 
        VALUES (NEW."ID_TEMUAN", NEW."LOG_KIRIM", CURRENT_TIMESTAMP);
    END IF;
    
    -- Check if WAKTU_TL_ATASAN is being updated
    IF NEW."WAKTU_TL_ATASAN" IS DISTINCT FROM OLD."WAKTU_TL_ATASAN" THEN
        INSERT INTO "LOG_TEMUAN" ("ID_TARGET", "LOG_KIRIM", "WAKTU") 
        VALUES (NEW."ID_TEMUAN", NEW."LOG_KIRIM", CURRENT_TIMESTAMP);
    END IF;
    
    -- Check if WAKTU_TL_AUDITOR is being updated
    IF NEW."WAKTU_TL_AUDITOR" IS DISTINCT FROM OLD."WAKTU_TL_AUDITOR" THEN
        INSERT INTO "LOG_TEMUAN" ("ID_TARGET", "LOG_KIRIM", "WAKTU") 
        VALUES (NEW."ID_TEMUAN", NEW."LOG_KIRIM", CURRENT_TIMESTAMP);
    END IF;
    
    -- Check if WAKTU_TL_LEADAUDITOR is being updated
    IF NEW."WAKTU_TL_LEADAUDITOR" IS DISTINCT FROM OLD."WAKTU_TL_LEADAUDITOR" THEN
        INSERT INTO "LOG_TEMUAN" ("ID_TARGET", "LOG_KIRIM", "WAKTU") 
        VALUES (NEW."ID_TEMUAN", NEW."LOG_KIRIM", CURRENT_TIMESTAMP);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_temuan_update
BEFORE UPDATE ON "TEMUAN_DETAIL"
FOR EACH ROW
EXECUTE FUNCTION log_temuan_trigger();
