ALTER TABLE "TEMUAN_DETAIL" 
ADD COLUMN "WAKTU_TL_ATASAN" TIMESTAMP NULL,
ADD COLUMN "WAKTU_TL_AUDITOR" TIMESTAMP NULL,
ADD COLUMN "WAKTU_TL_LEADAUDITOR" TIMESTAMP NULL;



CREATE OR REPLACE FUNCTION "LAST_MODIFY_TEMUAN_DETAIL_TINDAK_LANJUT"()
RETURNS TRIGGER AS $$
BEGIN

	SET TIME ZONE 'Asia/Jakarta';
    -- Check if kolom1 is being updated
    IF NEW."KETERANGAN_TL_ATASAN" IS DISTINCT FROM OLD."KETERANGAN_TL_ATASAN" THEN
        NEW."WAKTU_TL_ATASAN" = CURRENT_TIMESTAMP;
    END IF;
    
    -- Check if kolom2 is being updated
    IF NEW."KETERANGAN_TL_AUDITOR" IS DISTINCT FROM OLD."KETERANGAN_TL_AUDITOR" THEN
        NEW."WAKTU_TL_AUDITOR" = CURRENT_TIMESTAMP;
    END IF;
    
    -- Check if kolom3 is being updated
    IF NEW."KETERANGAN_TL_LEAD_AUDITOR" IS DISTINCT FROM OLD."KETERANGAN_TL_LEAD_AUDITOR" THEN
        NEW."WAKTU_TL_LEADAUDITOR" = CURRENT_TIMESTAMP;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER temuan_before_update_tl
BEFORE UPDATE ON "TEMUAN_DETAIL"
FOR EACH ROW
EXECUTE FUNCTION "LAST_MODIFY_TEMUAN_DETAIL_TINDAK_LANJUT"();



SELECT CURRENT_TIMESTAMP;